version: "3.3"

services:
  web:
    build: .

    env_file: .env

    ports:
      - "80:80"

    volumes:
      - shared-assets:/app/public/assets

  psp:
    build: ./psp

    env_file: .env

    # Use the RAILS_ENV value of the host machine
    environment:
      RAILS_ENV: $RAILS_ENV

    ports:
      - "8080:8080"

    volumes:
      - shared-assets:/app/public/assets

  api:
    build: ./api

    env_file: .env

    environment:
      RAILS_ENV: $RAILS_ENV

    ports:
      - "8081:8080"

  db:
    image: postgres:9.6

    # persist the database data
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  shared-assets:
  postgres-data: 
